# This workflow will test if packages with xitorch can be packaged with pyinstaller

name: packageability

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

jobs:

  binary:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout repo and submodules
      uses: actions/checkout@main
      with:
        submodules: recursive
        fetch-depth: '0'
    - name: Build SLDENSE and test requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
        python -m pip install pyinstaller
    - name: Create a dummy executable file
      run: |
        echo "import xitorch, xitorch.optimize, xitorch.integrate, xitorch.linalg, xitorch.interpolate; print('hello')" > dummy.py
    - name: Build the binary
      run: |
        pyinstaller dummy.py
    - name: Test the binary
      run: |
        ./dist/dummy/dummy
