name: Publish Python distributions to PyPI and TestPyPI

on:
  - push:
    branches: [ master ]
    tags: [ v* ]
  - workflow_dispatch:

jobs:
  build-n-publish:

    name: Build and publish Python distributions to PyPI and TestPyPI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        poetry-version: [1.2.2]

    steps:
      - uses: actions/checkout@master
      - name: Build and publish to Test PyPI
        if: ${{ !(startsWith(github.ref, 'refs/tags')) }}
        uses: JRubics/poetry-publish@v1.16
        with:
          python_version: ${{ matrix.python-version }}
          poetry_version: "==${{ matrix.poetry-version }}"
          plugins: "poetry-dynamic-versioning"
          pypi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
      - name: Build and publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: JRubics/poetry-publish@v1.16
        with:
          python_version: ${{ matrix.python-version }}
          poetry_version: "==${{ matrix.poetry-version }}"
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
          plugins: "poetry-dynamic-versioning"
